-- ============================================================
-- Real-Time Noise Monitoring System - MySQL Schema
-- Faculty of Artificial Intelligence, Taraba State University
-- ============================================================
-- Note: For Railway deployment, the database is already created
-- This schema creates tables in the existing database

-- ---------------------------------------------------------
-- Users: students, faculty administrators, system admins
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  full_name       VARCHAR(150) NOT NULL,
  email           VARCHAR(150) NOT NULL UNIQUE,
  password_hash   VARCHAR(255) NOT NULL,
  role            ENUM('student', 'administrator', 'system_admin') NOT NULL DEFAULT 'student',
  department      VARCHAR(150) DEFAULT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Sensor nodes (ESP8266 + LM393 physical units)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS sensor_nodes (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  sensor_code         VARCHAR(50) NOT NULL UNIQUE,      -- e.g. SN-LR-04
  api_key             VARCHAR(64) NOT NULL UNIQUE,       -- used by firmware to authenticate POSTs
  location            VARCHAR(150) NOT NULL,
  room_identifier     VARCHAR(100) NOT NULL,
  calibration_offset  DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  status              ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  last_seen           TIMESTAMP NULL DEFAULT NULL,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Noise readings (time-series sound pressure level data)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS noise_readings (
  id              BIGINT AUTO_INCREMENT PRIMARY KEY,
  sensor_id       INT NOT NULL,
  decibel_value   DECIMAL(5,2) NOT NULL,
  recorded_at     DATETIME NOT NULL,
  violation_flag  BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reading_sensor FOREIGN KEY (sensor_id)
    REFERENCES sensor_nodes(id) ON DELETE CASCADE,
  INDEX idx_sensor_time (sensor_id, recorded_at)
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Alert thresholds (configurable per sensor + time period)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS alert_thresholds (
  id                       INT AUTO_INCREMENT PRIMARY KEY,
  sensor_id                INT NOT NULL,
  label                    VARCHAR(100) DEFAULT 'Default',
  max_decibel              DECIMAL(5,2) NOT NULL,
  hysteresis_db            DECIMAL(4,2) NOT NULL DEFAULT 3.00,
  period_start             TIME NOT NULL DEFAULT '00:00:00',
  period_end               TIME NOT NULL DEFAULT '23:59:59',
  notification_recipients  JSON DEFAULT NULL,
  is_active                BOOLEAN NOT NULL DEFAULT TRUE,
  created_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_threshold_sensor FOREIGN KEY (sensor_id)
    REFERENCES sensor_nodes(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Alert logs (violation events + acknowledgement trail)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS alert_logs (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  threshold_id    INT NOT NULL,
  sensor_id       INT NOT NULL,
  reading_id      BIGINT DEFAULT NULL,
  decibel_value   DECIMAL(5,2) NOT NULL,
  user_id         INT DEFAULT NULL,          -- who acknowledged it
  triggered_at    DATETIME NOT NULL,
  acknowledged_at DATETIME DEFAULT NULL,
  status          ENUM('pending', 'acknowledged') NOT NULL DEFAULT 'pending',
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_alert_threshold FOREIGN KEY (threshold_id)
    REFERENCES alert_thresholds(id) ON DELETE CASCADE,
  CONSTRAINT fk_alert_sensor FOREIGN KEY (sensor_id)
    REFERENCES sensor_nodes(id) ON DELETE CASCADE,
  CONSTRAINT fk_alert_user FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Seed data: one demo admin account + two sensor nodes
-- Password for admin@fai.edu is "Admin123!" (bcrypt-style hash
-- generated by werkzeug at first run via seed_demo_data.py instead
-- of being hard-coded here, since Werkzeug hashes are versioned).
-- ---------------------------------------------------------
INSERT IGNORE INTO sensor_nodes (sensor_code, api_key, location, room_identifier, calibration_offset, status)
VALUES
  ('SN-LR-01', 'demo-key-lr01-change-me', 'Lecture Room 1, FAI Building', 'LR-01', 2.5, 'active'),
  ('SN-LAB-02', 'demo-key-lab02-change-me', 'AI Computer Lab, FAI Building', 'LAB-02', 1.0, 'active'),
  ('SN-LIB-03', 'demo-key-lib03-change-me', 'Silent Study Area, FAI Library', 'LIB-03', 0.5, 'active');

INSERT IGNORE INTO alert_thresholds (sensor_id, label, max_decibel, hysteresis_db, period_start, period_end)
SELECT id, 'Lecture hours limit', 65.00, 3.00, '08:00:00', '18:00:00' FROM sensor_nodes WHERE sensor_code = 'SN-LR-01';

INSERT IGNORE INTO alert_thresholds (sensor_id, label, max_decibel, hysteresis_db, period_start, period_end)
SELECT id, 'Lab session limit', 60.00, 3.00, '08:00:00', '20:00:00' FROM sensor_nodes WHERE sensor_code = 'SN-LAB-02';

INSERT IGNORE INTO alert_thresholds (sensor_id, label, max_decibel, hysteresis_db, period_start, period_end)
SELECT id, 'Silent area limit', 45.00, 2.00, '00:00:00', '23:59:59' FROM sensor_nodes WHERE sensor_code = 'SN-LIB-03';
